// Generated by CoffeeScript 1.4.0
(function() {
  var load_image, loader, main, poll;

  $(function() {
    return main();
  });

  main = function() {
    load_image('images/example.jpg');
    return poll();
  };

  poll = function() {
    return setTimeout(function() {
      console.log('do an ajax call');
      load_image('images/example.jpg');
      return poll();
    }, 30000);
  };

  load_image = function(url) {
    if ($('#pictures img').length > 0) {
      return $('#pictures img').fadeOut(2000, function() {
        $(this).remove();
        return loader(url);
      });
    } else {
      return loader(url);
    }
  };

  loader = function(url) {
    var img;
    img = new Image();
    $(img).hide();
    return $(img).load(function() {
      $('#pictures').append($(img));
      return $(img).fadeIn(2000);
    }).attr('src', url);
  };

}).call(this);
