// Generated by CoffeeScript 1.4.0
(function() {
  var load_image, main;

  $(function() {
    return main();
  });

  main = function() {
    return load_image('images/example.jpg');
  };

  load_image = function(url) {
    return $('#pictures img').fadeOut(2000, function() {
      var img;
      $(this).remove();
      img = new Image();
      $(img).hide();
      return $(img).load(function() {
        $('#pictures').append($(img));
        return $(img).fadeIn(2000);
      }).attr('src', url);
    });
  };

}).call(this);
