// Generated by CoffeeScript 1.4.0
(function() {
  var main;

  $(function() {
    return main();
  });

  main = function() {
    console.log($('body'));
    return console.log('loaded');
  };

}).call(this);
